### ISSUE TITLE
When used with a Binder to bind to an Integer field and the value length is > 3 digits, I get java.lang.NumberFormatException

### ISSUE THREAD

**Issue by wodencafe** [Ansku/numberfield#9]
Hello, thank you for the useful addon NumberField.

I am using **org.vaadin.ui.numberfield 0.2.0** with **Vaadin 8**

When used with the com.vaadin.data.Binder and bound to an Integer field on an entity, I receive the following exception:

```
java.lang.NumberFormatException: For input string: "2,003"                                                                                                                                           
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)                                                                                                                  
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)                                                                                                                            
        at java.lang.Double.parseDouble(Double.java:538)                                                                                                                                             
        at java.lang.Double.valueOf(Double.java:502)                                                                                                                                                 
        at org.vaadin.ui.NumberField.getValueAsFormattedDecimalNumber(NumberField.java:320)                                                                                                          
        at org.vaadin.ui.NumberField.updateFormattedValue(NumberField.java:307)                                                                                                                      
        at org.vaadin.ui.NumberField.lambda$0(NumberField.java:173)                                                                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                               
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                     
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                          
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)                                                                                                                     
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)                                                                                                                              
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)                                                                                                                              
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1033)                                                                                                    
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:144)                                                                                                                              
        at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:98)                                                                                                                       
        at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:47)                                                                                                                       
        at com.vaadin.data.Binder$BindingImpl.initFieldValue(Binder.java:893)                                                                                                                        
        at com.vaadin.data.Binder$BindingImpl.access$100(Binder.java:766)                                                                                                                            
        at com.vaadin.data.Binder$BindingBuilderImpl.bind(Binder.java:593)                                                                                                                           
        at com.cffnow.ui.controls.editors.base.IFieldRegistrarAspect.registerField(IFieldRegistrarAspect.java:29)                                                                                    
        at com.cffnow.ui.controls.editors.equipment.components.EquipmentEditor.getYearField(EquipmentEditor.java:288)                                                                                
```

So the integer value is 2003, but for some reason a comma is appearing, and causing a NumberFormatException.

I verified that when the value's length is 3 or less, this is not an issue.

**Comment by besatanas** [comment]
Hello Wodencafe,

This issue is due to the fact that the binder use the Local representation of number by default. So either you change your local settings to avoid thousans separators or you can use the following custom binder:

See this forum discussion : https://vaadin.com/forum/#!/thread/2237685

**Comment by besatanas** [comment]
But by the way, i'm reusing that issue, because I'm getting the same behaviour but with a real string.
In M software, I'm receiving string with differents formats, sub fields, lenght etc... and when decoding some area, if I got a missalignment or bad encoding of the text string, it's possible to assing a aphanumeric value to a numberField, and it's displayed as an error and prevend validation. That's fine, and I would like to keep that behaviour, because if I trap that issue before, I only display an empty field and it's less obvious to end user that there is a mistake in the value.

But is it possible to Catch and throw the exeption to let the program going forward.

Here are the logs and lines numbers.

`13:59:48,793 ERROR [stderr] (default task-51) java.lang.NumberFormatException: For input string: "999A"

13:59:48,793 ERROR [stderr] (default task-51) 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)

13:59:48,793 ERROR [stderr] (default task-51) 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)

13:59:48,793 ERROR [stderr] (default task-51) 	at java.lang.Double.parseDouble(Double.java:538)

13:59:48,793 ERROR [stderr] (default task-51) 	at java.lang.Double.valueOf(Double.java:502)

13:59:48,793 ERROR [stderr] (default task-51) 	at org.vaadin.ui.NumberField.getValueAsFormattedDecimalNumber(NumberField.java:320)

13:59:48,793 ERROR [stderr] (default task-51) 	at org.vaadin.ui.NumberField.updateFormattedValue(NumberField.java:307)

13:59:48,794 ERROR [stderr] (default task-51) 	at org.vaadin.ui.NumberField.lambda$0(NumberField.java:173)`
